# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'View Summary',
                'proxy': True,
                'verbose_name_plural': 'View Summary',
                'indexes': [],
            },
            bases=('blog.post',),
        ),
    ]
